---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yujing.
--- DateTime: 2020/4/7 1:38 下午
---
---
require("ecc")
require("bit")
local pub = {}
local priv = {}
local signature = {}
ecc_make_key(pub,priv)
print()
local hash = {}

-- just for test . this means "test"*8
--for i = 1 ,8 do
--    hash[(i-1)*4+1]= 116
--    hash[(i-1)*4+2]= 101
--    hash[(i-1)*4+3]= 115
--    hash[(i-1)*4+4]= 116
--end
hash = str2bytes("testtesttesttesttesttesttesttest")
print(bytes2hex(priv))
print(bytes2hex(pub))
ecdsa_sign(priv,hash,signature)
local sigstr = ""

for i = 1,64 do
    sigstr = sigstr ..string.format("%x",signature[i]/16)
    sigstr = sigstr ..string.format("%x",signature[i]%16)
end
print("signature ",string.lower(sigstr))
print(ecdsa_verify(pub,hash,signature))
